=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/capabilities.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "version": { "type": "string" },
    "only": { "type": "boolean" },
    "skip": { "type": "boolean" },
    "cypressTopWindowReplacement": { "type": "boolean" },
    "hostSdkVersion": {
      "type": "object",
      "properties": {
        "web": { "type": "string" },
        "android": { "type": "string" },
        "ios": { "type": "string" }
      },
      "additionalProperties": false
    },
    "checkIsSupported": {
      "type": "object",
      "properties": {
        "capabilityName": { "type": "string" },
        "domElementName": { "type": "string" },
        "expectedOutput": { "type": "string" },
        "toggleId": { "type": "string" },
        "version": { "type": "string" },
        "testUrlParams": { "$ref": "#/$defs/testUrlParams" }
      },
      "additionalProperties": false
    },
    "platforms": {
      "oneOf": [{ "type": "string" }, { "type": "array", "items": { "type": "string" } }]
    },
    "testUrlParams": { "$ref": "#/$defs/testUrlParams" },
    "testCases": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "title": { "type": "string" },
              "version": { "type": "string" },
              "hostSdkVersion": {
                "type": "object",
                "properties": {
                  "web": { "type": "string" },
                  "android": { "type": "string" },
                  "ios": { "type": "string" }
                },
                "additionalProperties": false
              },
              "platformsExcluded": {
                "type": "array",
                "items": { "type": "string" }
              },
              "only": { "type": "boolean" },
              "testUrlParams": { "$ref": "#/$defs/testUrlParams" },
              "expectedAlertValue": {
                "oneOf": [{ "type": "string" }, { "type": "array", "items": { "type": "string" } }]
              },
              "expectedWindowOpenTarget": { "type": "string" },
              "expectedIFrameTarget": { "type": "string" },
              "expectedSecondViewTarget": { "type": "string" },
              "modulesToDisable": {
                "type": "array",
                "items": { "type": "string" }
              },
              "skipForCallbackBasedRuns": { "type": "boolean" }
            },
            "required": ["title"]
          },
          {
            "type": "object",
            "oneOf": [
              {
                "properties": {
                  "type": { "const": "callResponse" },
                  "boxSelector": { "type": "string" },
                  "inputValue": {},
                  "skipJsonStringifyOnInputValue": { "type": "boolean" },
                  "checkboxState": { "type": "boolean" },
                  "expectedTestAppValue": { "type": "string" },
                  "isRequestPermissionCall": {
                    "type": "object",
                    "properties": {
                      "repeatRequestPermissionCall": { "type": "boolean" }
                    }
                  },
                  "requestPermissionBeforeThisCall": {
                    "type": "object",
                    "properties": {
                      "boxSelector": { "type": "string" },
                      "consentPermission": {
                        "oneOf": [{ "type": "boolean" }, { "type": "string", "enum": ["Allow"] }]
                      },
                      "expectedOutput": { "type": "string" }
                    },
                    "required": ["boxSelector", "consentPermission"]
                  }
                },
                "required": ["boxSelector"]
              },
              {
                "properties": {
                  "type": { "const": "raiseEvent" },
                  "eventName": { "type": "string" },
                  "eventData": {}
                },
                "required": ["eventName"]
              },
              {
                "properties": {
                  "type": { "const": "registerAndRaiseEvent" },
                  "boxSelector": { "type": "string" },
                  "inputValue": {},
                  "eventName": { "type": "string" },
                  "eventData": {},
                  "expectedAlertValueOnRegistration": {
                    "oneOf": [{ "type": "string" }, { "type": "array", "items": { "type": "string" } }]
                  },
                  "expectedTestAppValue": { "type": "string" }
                },
                "required": ["boxSelector", "eventName"]
              }
            ]
          }
        ],
        "unevaluatedProperties": false,
        "required": ["type"]
      }
    },
    "featureTests": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "feature": {
            "type": "object",
            "properties": {
              "id": { "type": "string" },
              "version": { "type": "number" }
            },
            "required": ["id", "version"],
            "additionalProperties": false
          },
          "testCases": {
            "$ref": "#/properties/testCases"
          }
        },
        "required": ["feature", "testCases"],
        "additionalProperties": false
      }
    }
  },
  "anyOf": [
    {
      "required": ["name", "testCases"]
    },
    {
      "required": ["name", "featureTests"]
    }
  ],
  "required": ["name"],
  "additionalProperties": false,
  "$defs": {
    "testUrlParams": {
      "type": "array",
      "items": {
        "type": "array",
        "prefixItems": [
          { "enum": ["env", "appDefOverrides", "sessionId", "frameContext", "hostClientType", "hostView"] },
          { "type": "string" }
        ]
      }
    }
  }
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/clipboard.json
{
  "name": "Clipboard",
  "version": ">2.14.0",
  "platforms": "*",
  "testCases": [
    {
      "title": "Copy Text - success",
      "type": "callResponse",
      "boxSelector": "#box_copyText",
      "inputValue": "Hello Team",
      "expectedTestAppValue": "true",
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "Copy Text - failure",
      "type": "callResponse",
      "boxSelector": "#box_copyText",
      "inputValue": "\"\"",
      "skipJsonStringifyOnInputValue": true,
      "expectedTestAppValue": "Error: String can't be empty",
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "Copy JPEG Image - success",
      "type": "callResponse",
      "boxSelector": "#box_copyImage",
      "inputValue": "image/jpeg",
      "expectedTestAppValue": "true",
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "Copy PNG Image - success",
      "type": "callResponse",
      "boxSelector": "#box_copyImage",
      "inputValue": "image/png",
      "expectedTestAppValue": "true",
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "Copy Image - failure",
      "type": "callResponse",
      "boxSelector": "#box_copyImage",
      "inputValue": "\"\"",
      "skipJsonStringifyOnInputValue": true,
      "expectedTestAppValue": "Error: mimeType can't be empty",
      "skipForCallbackBasedRuns": true
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/copilot.json
{
  "name": "copilot",
  "platforms": "*",
  "version": ">=2.22.0",
  "testCases": [
    {
      "title": "copilot hasM365Chat license API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_CheckIfUserOfTheM365ChatAppHasLicense",
      "expectedTestAppValue": "User does have a license for the M365 Chat app"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/pages.currentApp.json
{
  "name": "Pages CurrentApp",
  "platforms": "Web",
  "checkIsSupported": {
    "capabilityName": "PageCurrentApp",
    "expectedOutput": "Pages.currentApp module is supported",
    "testUrlParams": [],
    "version": ">2.3.0"
  },
  "testCases": [
    {
      "title": "navigateTo API Call - Success",
      "type": "callResponse",
      "version": ">2.3.0",
      "boxSelector": "#box_navigateTo",
      "inputValue": {
        "pageId": "tasklist123",
        "subPageId": "task456"
      },
      "expectedAlertValue": "navigateToApp called with {\"appId\":\"com.example.metaostestapp.test\",\"pageId\":\"tasklist123\",\"subPageId\":\"task456\"}",
      "expectedTestAppValue": "Completed"
    },
    {
      "title": "navigateTo API Call no subPageID- Success",
      "type": "callResponse",
      "version": ">2.3.0",
      "boxSelector": "#box_navigateTo",
      "inputValue": {
        "pageId": "tasklist123"
      },
      "expectedAlertValue": "navigateToApp called with {\"appId\":\"com.example.metaostestapp.test\",\"pageId\":\"tasklist123\"}",
      "expectedTestAppValue": "Completed"
    },
    {
      "title": "navigateTo API Call - Failure",
      "type": "callResponse",
      "version": ">2.3.0",
      "boxSelector": "#box_navigateTo",
      "inputValue": {},
      "expectedTestAppValue": "Error: PageID are required."
    },
    {
      "title": "navigateToDefaultPage API Call - Success",
      "type": "callResponse",
      "version": ">2.3.0",
      "boxSelector": "#box_navigateToDefaultPage",
      "expectedAlertValue": "navigateToApp called with {\"appId\":\"com.example.metaostestapp.test\",\"pageId\":\"serverUrl\"}",
      "expectedTestAppValue": "Completed"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/visualMedia.image.json
{
  "name": "VisualMedia Image",
  "platforms": "iOS",
  "version": ">=2.18.0",
  "checkIsSupported": {
    "capabilityName": "VisualMediaImage",
    "expectedOutput": "VisualMedia.image module is supported"
  },
  "testCases": [
    {
      "title": "captureImages API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_captureImages",
      "inputValue": {
        "maxVisualMediaCount": 9,
        "sourceProps": {
          "source": 1,
          "cameraRestriction": 1
        }
      },
      "requestPermissionBeforeThisCall": {
        "boxSelector": "#box_requestVisualMediaPermission",
        "consentPermission": "Allow",
        "expectedOutput": "true"
      },
      "expectedAlertValue": "visualMedia.image.captureImages is called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "[content: \"content1\", size: 4, name: a_pic, mimeType: jpg],[content: \"content2\", size: 1, name: b_pic, mimeType: jpg],"
    },
    {
      "title": "uploadImages API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_uploadImages",
      "inputValue": {
        "maxVisualMediaCount": 9,
        "sourceProps": {
          "source": 2
        }
      },
      "requestPermissionBeforeThisCall": {
        "boxSelector": "#box_requestVisualMediaPermission",
        "consentPermission": "Allow",
        "expectedOutput": "true"
      },
      "expectedAlertValue": "visualMedia.image.uploadImages is called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "[content: \"content1\", size: 4, name: a_pic, mimeType: jpg],[content: \"content2\", size: 1, name: b_pic, mimeType: jpg],"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/video.sharedFrame.json
{
  "name": "Video SharedFrame",
  "platforms": "Web",
  "testUrlParams": [["frameContext", "sidePanel"]],
  "version": ">2.11.0",
  "testCases": [
    {
      "title": "video.sharedFrame.registerForVideoFrame - Success",
      "type": "callResponse",
      "boxSelector": "#box_videoSharedFrameRegisterForVideoFrame",
      "modulesToDisable": ["videoMediaStream"],
      "expectedTestAppValue": "Registration attempt has been initiated. If successful, this message will change when it is invoked on video frame received.",
      "expectedAlertValue": "sharedFrame.registerForVideoFrame called with config: {\"format\":\"NV12\"}"
    },
    {
      "title": "videoEx.sharedFrame.registerForVideoFrame - Success",
      "type": "callResponse",
      "version": ">2.12.0",
      "boxSelector": "#box_videoExSharedFrameRegisterForVideoFrame1",
      "modulesToDisable": ["videoMediaStream"],
      "expectedTestAppValue": "Registration attempt has been initiated. If successful, this message will change when it is invoked on video frame received.",
      "expectedAlertValue": "sharedFrame.registerForVideoFrame called with config: {\"format\":\"NV12\",\"requireCameraStream\":false,\"audioInferenceModel\":{}}"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/files.json
{
  "name": "Files",
  "version": ">2.0.0-beta.0",
  "platforms": "*",
  "testCases": [
    {
      "title": "openFilePreview API Call - Success",
      "type": "callResponse",
      "version": ">2.0.0-beta.2",
      "boxSelector": "#box_openFilePreview",
      "inputValue": {
        "entityId": "testEntityId",
        "title": "testTitle",
        "description": "testDescription",
        "type": "testType",
        "objectUrl": "testObjectUrl",
        "downloadUrl": "testDownloadUrl",
        "webPreviewUrl": "testWebPreviewUrl",
        "baseUrl": "testBaseUrl",
        "editFile": true,
        "subEntityId": "testSubEntityId",
        "viewerAction": "edit",
        "fileOpenPreference": "web"
      },
      "expectedAlertValue": "openFilePreview called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "Called"
    },
    {
      "title": "openFilePreview API Call - Success",
      "type": "callResponse",
      "version": "2.0.0-beta.2",
      "boxSelector": "#box_openFilePreview",
      "inputValue": {
        "entityId": "testEntityId",
        "title": "testTitle",
        "description": "testDescription",
        "type": "testType",
        "objectUrl": "testObjectUrl",
        "downloadUrl": "testDownloadUrl",
        "webPreviewUrl": "testWebPreviewUrl",
        "baseUrl": "testBaseUrl",
        "editFile": true,
        "subEntityId": "testSubEntityId",
        "viewerAction": "edit",
        "fileOpenPreference": "web"
      },
      "expectedAlertValue": "openFilePreview called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "openFilePreview() was called, but there was no response from the Host SDK."
    },
    {
      "title": "getCloudStorageFolders API Call - Success",
      "type": "callResponse",
      "version": ">2.0.0-beta.2",
      "boxSelector": "#box_getCloudStorageFolders2",
      "inputValue": "testChannelId",
      "expectedAlertValue": "getCloudStorageFolders called with channelId: testChannelId",
      "expectedTestAppValue": "[{\"id\":\"testId\",\"title\":\"testTitle\",\"folderId\":\"testFolderId\",\"providerType\":2,\"providerCode\":\"GOOGLEDRIVE\",\"ownerDisplayName\":\"testOwnerDisplayName\"}]"
    },
    {
      "title": "getCloudStorageFolders API Call - Success",
      "type": "callResponse",
      "version": "2.0.0-beta.2",
      "boxSelector": "#box_getCloudStorageFolders",
      "inputValue": "testChannelId",
      "expectedAlertValue": "getCloudStorageFolders called with channelId: \"testChannelId\"",
      "expectedTestAppValue": "[{\"id\":\"testId\",\"title\":\"testTitle\",\"folderId\":\"testFolderId\",\"providerType\":2,\"providerCode\":\"GOOGLEDRIVE\",\"ownerDisplayName\":\"testOwnerDisplayName\"}]"
    },
    {
      "title": "addCloudStorageFolder API Call - Success",
      "type": "callResponse",
      "version": ">2.0.0-beta.2",
      "boxSelector": "#box_addCloudStorageFolder2",
      "inputValue": "testChannelId",
      "expectedAlertValue": "addCloudStorageFolder called with channelId: testChannelId",
      "expectedTestAppValue": "{\"isFolderAdded\":true,\"folders\":[{\"id\":\"testId\",\"title\":\"testTitle\",\"folderId\":\"testFolderId\",\"providerType\":2,\"providerCode\":\"GOOGLEDRIVE\",\"ownerDisplayName\":\"testOwnerDisplayName\"}]}"
    },
    {
      "title": "addCloudStorageFolder API Call - Success",
      "type": "callResponse",
      "version": "2.0.0-beta.2",
      "boxSelector": "#box_addCloudStorageFolder",
      "inputValue": "testChannelId",
      "expectedAlertValue": "addCloudStorageFolder called with channelId: \"testChannelId\"",
      "expectedTestAppValue": "{\"isFolderAdded\":true,\"folders\":[{\"id\":\"testId\",\"title\":\"testTitle\",\"folderId\":\"testFolderId\",\"providerType\":2,\"providerCode\":\"GOOGLEDRIVE\",\"ownerDisplayName\":\"testOwnerDisplayName\"}]}"
    },
    {
      "title": "deleteCloudStorageFolder API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_deleteCloudStorageFolder",
      "inputValue": {
        "channelId": "testChannelId",
        "folderToDelete": {
          "id": "testId",
          "title": "testTitle",
          "folderId": "testFolderId",
          "providerType": 2,
          "providerCode": "GOOGLEDRIVE",
          "ownerDisplayName": "testOwnerDisplayName"
        }
      },
      "expectedAlertValue": "deleteCloudStorageFolder called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "true"
    },
    {
      "title": "copyMoveFiles API Call - Success",
      "version": ">2.0.0-beta.2",
      "type": "callResponse",
      "platformsExcluded": ["iOS"],
      "boxSelector": "#box_copyMoveFiles",
      "inputValue": {
        "selectedFiles": [
          {
            "id": "123",
            "lastModifiedTime": "2021-04-14T15:08:35Z",
            "size": 32,
            "objectUrl": "abc.com",
            "title": "file",
            "isSubdirectory": false,
            "type": "type"
          }
        ],
        "providerCode": "DROPBOX",
        "destinationFolder": {
          "id": "123",
          "lastModifiedTime": "2021-04-14T15:08:35Z",
          "size": 32,
          "objectUrl": "abc.com",
          "title": "file",
          "isSubdirectory": false,
          "type": "type"
        },
        "destinationProviderCode": "GOOGLEDRIVE",
        "isMove": false
      },
      "expectedAlertValue": "copyMoveFiles called with ##JSON_INPUT_VALUE##"
    },
    {
      "title": "openCloudStorageFile API Call - Success",
      "type": "callResponse",
      "platformsExcluded": ["iOS"],
      "boxSelector": "#box_openCloudStorageFile",
      "inputValue": {
        "file": {
          "id": "test1",
          "title": "test.pptx",
          "isSubdirectory": false,
          "type": ".pptx",
          "size": 100,
          "objectUrl": "https://api.com/test.pptx",
          "lastModifiedTime": "2021-04-14T15:08:35Z"
        },
        "providerCode": "BOX"
      },
      "expectedAlertValue": "openCloudStorageFile called with ##JSON_INPUT_VALUE##"
    },
    {
      "title": "getExternalProviders API Call - Success",
      "type": "callResponse",
      "platformsExcluded": ["iOS"],
      "version": ">2.0.0",
      "boxSelector": "#box_getExternalProviders",
      "checkboxState": true,
      "expectedAlertValue": "getExternalProviders called",
      "expectedTestAppValue": "[{\"name\":\"firstProvider\",\"description\":\"dDesc\",\"thumbnails\":[],\"providerCode\":\"GOOGLEDRIVE\",\"providerType\":2}]"
    },
    {
      "title": "getCloudStorageFolderContents API Call - Success",
      "type": "callResponse",
      "platformsExcluded": ["iOS"],
      "version": ">2.0.0-beta.2",
      "boxSelector": "#box_getCloudStorageFolderContents",
      "inputValue": {
        "folder": {
          "id": "test1",
          "title": "test.pptx",
          "isSubdirectory": true,
          "type": ".pptx",
          "size": 100,
          "objectUrl": "https://api.com/test.pptx",
          "lastModifiedTime": "2021-04-14T15:08:35Z"
        },
        "providerCode": "BOX"
      },
      "expectedAlertValue": "getCloudStorageFolderContents called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "[{\"id\":\"test\",\"isSubdirectory\":false,\"lastModifiedTime\":\"23/06\",\"type\":\"ext\",\"size\":50,\"objectUrl\":\"object\",\"title\":\"testtitle\"}]"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/profile.json
{
  "name": "Profile",
  "platforms": "Web",
  "version": ">2.5.0",
  "checkIsSupported": {
    "domElementName": "checkCapabilityProfile"
  },
  "testCases": [
    {
      "title": "showProfile API Call - Success",
      "type": "callResponse",
      "hostSdkVersion": {
        "web": "<9.15.0"
      },
      "boxSelector": "#box_showProfile",
      "inputValue": {
        "modality": "Card",
        "persona": {
          "identifiers": {
            "Smtp": "test@microsoft.com"
          }
        },
        "targetElementBoundingRect": {
          "x": 0,
          "y": 0,
          "width": 0,
          "height": 0
        },
        "triggerType": "MouseClick"
      },
      "expectedAlertValue": "showProfile called with {\"modality\":\"Card\",\"persona\":{\"identifiers\":{\"Smtp\":\"test@microsoft.com\"}},\"targetElementBoundingRect\":{\"x\":243,\"y\":0,\"width\":0,\"height\":0,\"top\":0,\"right\":243,\"bottom\":0,\"left\":243},\"triggerType\":\"MouseClick\"}"
    },
    {
      "title": "showProfile API Call - Success",
      "type": "callResponse",
      "hostSdkVersion": {
        "web": ">9.15.1"
      },
      "boxSelector": "#box_showProfile",
      "inputValue": {
        "modality": "Card",
        "persona": {
          "identifiers": {
            "Smtp": "test@microsoft.com"
          }
        },
        "targetElementBoundingRect": {
          "x": 0,
          "y": 0,
          "width": 0,
          "height": 0
        },
        "triggerType": "MouseClick"
      },
      "expectedAlertValue": "regex:showProfile called with .*\"Smtp\":\"test@microsoft.com\".*\"triggerType\":\"MouseClick\""
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/monetization.json
{
  "name": "Monetization",
  "platforms": "Web",
  "checkIsSupported": {
    "domElementName": "checkCapabilityMonetization",
    "version": "1.x || >2.0.0-beta.2"
  },
  "testCases": [
    {
      "title": "openPurchaseExperience API Call - Success",
      "type": "callResponse",
      "version": "1.x || >2.0.0-beta.2",
      "boxSelector": "#box_monetization_openPurchaseExperience",
      "inputValue": {
        "planId": "abc",
        "term": "001"
      },
      "expectedAlertValue": "openPurchaseExperience called with ##JSON_INPUT_VALUE##"
    },

    {
      "title": "openPurchaseExperience API Call - Success",
      "type": "callResponse",
      "version": "2.0.0-beta.2",
      "boxSelector": "#box_monetization_openPurchaseExperience",
      "expectedAlertValue": "openPurchaseExperience called with undefined"
    }
  ]
}
