=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/capabilities.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "version": { "type": "string" },
    "only": { "type": "boolean" },
    "skip": { "type": "boolean" },
    "cypressTopWindowReplacement": { "type": "boolean" },
    "hostSdkVersion": {
      "type": "object",
      "properties": {
        "web": { "type": "string" },
        "android": { "type": "string" },
        "ios": { "type": "string" }
      },
      "additionalProperties": false
    },
    "checkIsSupported": {
      "type": "object",
      "properties": {
        "capabilityName": { "type": "string" },
        "domElementName": { "type": "string" },
        "expectedOutput": { "type": "string" },
        "toggleId": { "type": "string" },
        "version": { "type": "string" },
        "testUrlParams": { "$ref": "#/$defs/testUrlParams" }
      },
      "additionalProperties": false
    },
    "platforms": {
      "oneOf": [{ "type": "string" }, { "type": "array", "items": { "type": "string" } }]
    },
    "testUrlParams": { "$ref": "#/$defs/testUrlParams" },
    "testCases": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "title": { "type": "string" },
              "version": { "type": "string" },
              "hostSdkVersion": {
                "type": "object",
                "properties": {
                  "web": { "type": "string" },
                  "android": { "type": "string" },
                  "ios": { "type": "string" }
                },
                "additionalProperties": false
              },
              "platformsExcluded": {
                "type": "array",
                "items": { "type": "string" }
              },
              "only": { "type": "boolean" },
              "testUrlParams": { "$ref": "#/$defs/testUrlParams" },
              "expectedAlertValue": {
                "oneOf": [{ "type": "string" }, { "type": "array", "items": { "type": "string" } }]
              },
              "expectedWindowOpenTarget": { "type": "string" },
              "expectedIFrameTarget": { "type": "string" },
              "expectedSecondViewTarget": { "type": "string" },
              "modulesToDisable": {
                "type": "array",
                "items": { "type": "string" }
              },
              "skipForCallbackBasedRuns": { "type": "boolean" }
            },
            "required": ["title"]
          },
          {
            "type": "object",
            "oneOf": [
              {
                "properties": {
                  "type": { "const": "callResponse" },
                  "boxSelector": { "type": "string" },
                  "inputValue": {},
                  "skipJsonStringifyOnInputValue": { "type": "boolean" },
                  "checkboxState": { "type": "boolean" },
                  "expectedTestAppValue": { "type": "string" },
                  "isRequestPermissionCall": {
                    "type": "object",
                    "properties": {
                      "repeatRequestPermissionCall": { "type": "boolean" }
                    }
                  },
                  "requestPermissionBeforeThisCall": {
                    "type": "object",
                    "properties": {
                      "boxSelector": { "type": "string" },
                      "consentPermission": {
                        "oneOf": [{ "type": "boolean" }, { "type": "string", "enum": ["Allow"] }]
                      },
                      "expectedOutput": { "type": "string" }
                    },
                    "required": ["boxSelector", "consentPermission"]
                  }
                },
                "required": ["boxSelector"]
              },
              {
                "properties": {
                  "type": { "const": "raiseEvent" },
                  "eventName": { "type": "string" },
                  "eventData": {}
                },
                "required": ["eventName"]
              },
              {
                "properties": {
                  "type": { "const": "registerAndRaiseEvent" },
                  "boxSelector": { "type": "string" },
                  "inputValue": {},
                  "eventName": { "type": "string" },
                  "eventData": {},
                  "expectedAlertValueOnRegistration": {
                    "oneOf": [{ "type": "string" }, { "type": "array", "items": { "type": "string" } }]
                  },
                  "expectedTestAppValue": { "type": "string" }
                },
                "required": ["boxSelector", "eventName"]
              }
            ]
          }
        ],
        "unevaluatedProperties": false,
        "required": ["type"]
      }
    },
    "featureTests": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "feature": {
            "type": "object",
            "properties": {
              "id": { "type": "string" },
              "version": { "type": "number" }
            },
            "required": ["id", "version"],
            "additionalProperties": false
          },
          "testCases": {
            "$ref": "#/properties/testCases"
          }
        },
        "required": ["feature", "testCases"],
        "additionalProperties": false
      }
    }
  },
  "anyOf": [
    {
      "required": ["name", "testCases"]
    },
    {
      "required": ["name", "featureTests"]
    }
  ],
  "required": ["name"],
  "additionalProperties": false,
  "$defs": {
    "testUrlParams": {
      "type": "array",
      "items": {
        "type": "array",
        "prefixItems": [
          { "enum": ["env", "appDefOverrides", "sessionId", "frameContext", "hostClientType", "hostView"] },
          { "type": "string" }
        ]
      }
    }
  }
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/teams.fullTrust.joinedTeams.json
{
  "name": "Teams FullTrust JoinedTeams",
  "platforms": "Web",
  "version": ">2.0.0-beta.0",
  "testCases": [
    {
      "title": "getUserJoinedTeams API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_getUserJoinedTeams",
      "inputValue": {
        "favoriteTeamsOnly": true
      },
      "expectedAlertValue": "getUserJoinedTeams called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "{\"userJoinedTeams\":[{\"teamId\":\"testTeamId\",\"teamName\":\"testTeamName\"}]}"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/nestedAppAuth.json
{
  "name": "nestedAppAuth",
  "platforms": "*",
  "version": ">=2.22.0",
  "cypressTopWindowReplacement": true,
  "testCases": [
    {
      "title": "nestedAppAuth isNAAChannelRecommended API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_checkIsNAAChannelRecommended",
      "expectedTestAppValue": "NAA channel is recommended"
    },
    {
      "title": "nestedAppAuth - send message to NAA bridge from parent window",
      "type": "callResponse",
      "boxSelector": "#box_sendMessageToNestedAppAuthBridge",
      "inputValue": {
        "messageType": "NestedAppAuthRequest",
        "method": "GetToken",
        "sendTime": 1732269811006,
        "clientLibrary": "MetaOS",
        "clientLibraryVersion": "1.0.0",
        "requestId": "684352c2-7ab7-4def-b7e1-XXXXXXXXXXX",
        "tokenParams": { "correlationId": "39dc85fe-9054-11ed-a1eb-XXXXXXXXXXX" }
      },
      "expectedAlertValue": "nestedAppAuth.execute called with payload: ##JSON_INPUT_VALUE##, origin: https://localhost:4000/, isTrustedOrigin: true",
      "expectedTestAppValue": "\"{\\\"messageType\\\":\\\"NestedAppAuthResponse\\\",\\\"requestId\\\":\\\"684352c2-7ab7-4def-b7e1-XXXXXXXXXXX\\\",\\\"success\\\":true,\\\"initContext\\\":{\\\"sdkName\\\":\\\"OfficeAuth\\\",\\\"sdkVersion\\\":\\\"16.0.18015.15000\\\",\\\"capabilities\\\":{\\\"queryAccount\\\":false},\\\"accountContext\\\":{\\\"homeAccountId\\\":\\\"bb5r835b-XXXX\\\",\\\"environment\\\":\\\"login.windows.net\\\",\\\"tenantId\\\":\\\"2855cd1be\\\"}}}\""
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/pages.tabs.json
{
  "name": "Pages Tabs",
  "platforms": "Web",
  "checkIsSupported": {
    "capabilityName": "PageTabs",
    "expectedOutput": "Pages.tabs module is not supported"
  },
  "testCases": [
    {
      "title": "navigateToTab API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_navigateToTab",
      "inputValue": {
        "tabName": "TestTab",
        "internalTabInstanceId": "23",
        "channelIsFavorite": true,
        "url": "https://test.com"
      },
      "expectedAlertValue": "navigateToTab called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "Completed"
    },
    {
      "title": "getTabInstance API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_getTabInstance",
      "inputValue": {
        "favoriteTeamsOnly": true
      },
      "expectedAlertValue": "getTabInstances called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "{\"teamTabs\":[{\"tabName\":\"dummy1\",\"channelId\":\"1\"},{\"tabName\":\"dummy2\",\"channelId\":\"1\"}]}"
    },
    {
      "title": "getMRUTabInstance API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_getMRUTabInstance",
      "inputValue": {
        "favoriteTeamsOnly": true
      },
      "expectedAlertValue": "getMruTabInstances called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "{\"teamTabs\":[{\"tabName\":\"dummy1\",\"channelId\":\"1\"},{\"tabName\":\"dummy2\",\"channelId\":\"1\"}]}"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/barCode.json
{
  "name": "BarCode",
  "platforms": "Web",
  "version": ">=2.1.0",
  "checkIsSupported": {
    "domElementName": "checkBarCodeCapability",
    "expectedOutput": "BarCode is not supported"
  },
  "testCases": [
    {
      "title": "requestBarCodePermission API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_requestBarCodePermission",
      "isRequestPermissionCall": { "repeatRequestPermissionCall": false },
      "expectedTestAppValue": "true",
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "repeated requestBarCodePermission API Call with no dialog- Success",
      "type": "callResponse",
      "boxSelector": "#box_requestBarCodePermission",
      "isRequestPermissionCall": { "repeatRequestPermissionCall": true },
      "expectedTestAppValue": "true",
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "hasBarCodePermission API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_hasBarCodePermission",
      "expectedTestAppValue": "false",
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "scanBarCode API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_scanBarCode",
      "requestPermissionBeforeThisCall": {
        "boxSelector": "#box_requestBarCodePermission",
        "consentPermission": true
      },
      "inputValue": {},
      "expectedTestAppValue": "\"scannedCode\"",
      "expectedAlertValue": ["scanBarCode called with {}"],
      "skipForCallbackBasedRuns": true
    },
    {
      "title": "scanBarCode API Call - Failure",
      "type": "callResponse",
      "version": ">2.16.0",
      "boxSelector": "#box_scanBarCode",
      "requestPermissionBeforeThisCall": {
        "boxSelector": "#box_requestBarCodePermission",
        "consentPermission": false
      },
      "inputValue": {},
      "expectedTestAppValue": "Error: {\"errorCode\":1000,\"message\":\"user has explicitly not consented for device permission\"}",
      "skipForCallbackBasedRuns": true
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/call.json
{
  "name": "Call",
  "platforms": "Web",
  "version": ">=2.0.0",
  "checkIsSupported": {
    "domElementName": "checkCapabilityCall"
  },
  "testCases": [
    {
      "title": "startCall API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_startCall",
      "inputValue": {
        "targets": ["user1", "user2"],
        "requestedModalities": ["video"],
        "source": "source"
      },
      "expectedAlertValue": "startCall called with ##JSON_INPUT_VALUE##",
      "expectedTestAppValue": "result: true",
      "skipForCallbackBasedRuns": true
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/marketplace.json
{
  "name": "Marketplace",
  "platforms": "Web",
  "version": ">2.12.0",
  "checkIsSupported": {
    "capabilityName": "Marketplace",
    "toggleId": "marketplaceToggle",
    "expectedOutput": "marketplace module is not supported"
  },
  "testCases": [
    {
      "title": "GetCart API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_getCart",
      "expectedTestAppValue": "{\"id\":\"90dccefe-d23a-497d-9cb7-881bb5aaf729\",\"version\":{\"majorVersion\":1,\"minorVersion\":0},\"cartInfo\":{\"status\":\"Open\",\"market\":\"US\",\"currency\":\"USD\",\"intent\":\"TeamsAdminUser\",\"locale\":\"en-US\",\"createdAt\":\"2021-09-30T15:00:00.000Z\",\"updatedAt\":\" 2021-09-30T15:00:00.000Z\"},\"cartItems\":[{\"id\":\"1\",\"name\":\"Item 1\",\"price\":10,\"quantity\":1,\"accessories\":[{\"id\":\"11\",\"name\":\"Item 11\",\"price\":5,\"quantity\":1,\"imageURL\":\"https://via.placeholder.com/150\"}]}]}"
    },
    {
      "title": "AddOrUpdateCartItems API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_addOrUpdateCartItems",
      "inputValue": {
        "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729",
        "cartItems": [
          {
            "id": "2",
            "name": "Item 1",
            "price": 10,
            "quantity": 1,
            "accessories": [{ "id": "11", "name": "Item 11", "price": 5, "quantity": 1 }]
          }
        ]
      },
      "expectedTestAppValue": "{\"id\":\"90dccefe-d23a-497d-9cb7-881bb5aaf729\",\"version\":{\"majorVersion\":1,\"minorVersion\":0},\"cartInfo\":{\"status\":\"Open\",\"market\":\"US\",\"currency\":\"USD\",\"intent\":\"TeamsAdminUser\",\"locale\":\"en-US\",\"createdAt\":\"2021-09-30T15:00:00.000Z\",\"updatedAt\":\" 2021-09-30T15:00:00.000Z\"},\"cartItems\":[{\"id\":\"1\",\"name\":\"Item 1\",\"price\":10,\"quantity\":1,\"accessories\":[{\"id\":\"11\",\"name\":\"Item 11\",\"price\":5,\"quantity\":1,\"imageURL\":\"https://via.placeholder.com/150\"}]},{\"id\":\"2\",\"name\":\"Item 1\",\"price\":10,\"quantity\":1,\"accessories\":[{\"id\":\"11\",\"name\":\"Item 11\",\"price\":5,\"quantity\":1}]}]}"
    },
    {
      "title": "AddOrUpdateCartItems API Call - Invalid Quantity",
      "type": "callResponse",
      "boxSelector": "#box_addOrUpdateCartItems",
      "inputValue": {
        "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729",
        "cartItems": [
          {
            "id": "2",
            "name": "Item 1",
            "price": 10,
            "quantity": 1,
            "accessories": [{ "id": "11", "name": "Item 11", "price": 5, "quantity": 0 }]
          }
        ]
      },
      "expectedTestAppValue": "Error: Error: quantity 0 must be an integer greater than 0"
    },
    {
      "title": "AddOrUpdateCartItems API Call - Invalid Price",
      "type": "callResponse",
      "boxSelector": "#box_addOrUpdateCartItems",
      "inputValue": {
        "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729",
        "cartItems": [
          {
            "id": "2",
            "name": "Item 1",
            "price": 10,
            "quantity": 1,
            "accessories": [{ "id": "11", "name": "Item 11", "price": -5, "quantity": 0 }]
          }
        ]
      },
      "expectedTestAppValue": "Error: Error: price -5 must be a number not less than 0"
    },
    {
      "title": "AddOrUpdateCartItems API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_addOrUpdateCartItems",
      "inputValue": {
        "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729",
        "cartItems": [
          {
            "id": "2",
            "name": "Item 1",
            "price": 10,
            "quantity": 1,
            "accessories": [{ "id": "11", "name": "Item 11", "price": 5, "quantity": 1 }]
          }
        ]
      },
      "expectedTestAppValue": "{\"id\":\"90dccefe-d23a-497d-9cb7-881bb5aaf729\",\"version\":{\"majorVersion\":1,\"minorVersion\":0},\"cartInfo\":{\"status\":\"Open\",\"market\":\"US\",\"currency\":\"USD\",\"intent\":\"TeamsAdminUser\",\"locale\":\"en-US\",\"createdAt\":\"2021-09-30T15:00:00.000Z\",\"updatedAt\":\" 2021-09-30T15:00:00.000Z\"},\"cartItems\":[{\"id\":\"1\",\"name\":\"Item 1\",\"price\":10,\"quantity\":1,\"accessories\":[{\"id\":\"11\",\"name\":\"Item 11\",\"price\":5,\"quantity\":1,\"imageURL\":\"https://via.placeholder.com/150\"}]},{\"id\":\"2\",\"name\":\"Item 1\",\"price\":10,\"quantity\":1,\"accessories\":[{\"id\":\"11\",\"name\":\"Item 11\",\"price\":5,\"quantity\":1}]}]}"
    },
    {
      "title": "RemoveCartItems API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_removeCartItems",
      "inputValue": { "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729", "cartItemIds": ["1"] },
      "expectedTestAppValue": "{\"id\":\"90dccefe-d23a-497d-9cb7-881bb5aaf729\",\"version\":{\"majorVersion\":1,\"minorVersion\":0},\"cartInfo\":{\"status\":\"Open\",\"market\":\"US\",\"currency\":\"USD\",\"intent\":\"TeamsAdminUser\",\"locale\":\"en-US\",\"createdAt\":\"2021-09-30T15:00:00.000Z\",\"updatedAt\":\" 2021-09-30T15:00:00.000Z\"},\"cartItems\":[]}"
    },
    {
      "title": "AddOrUpdateCartItems API Call - Invalid ID",
      "type": "callResponse",
      "boxSelector": "#box_addOrUpdateCartItems",
      "inputValue": {
        "cartId": "90dccefe",
        "cartItems": [
          {
            "id": "2",
            "name": "Item 1",
            "price": 10,
            "quantity": 1,
            "accessories": [{ "id": "11", "name": "Item 11", "price": 5, "quantity": 1 }]
          }
        ]
      },
      "expectedTestAppValue": "Error: Error: id must be a valid UUID"
    },
    {
      "title": "AddOrUpdateCartItems API Call - Empty Array",
      "type": "callResponse",
      "boxSelector": "#box_addOrUpdateCartItems",
      "inputValue": { "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729", "cartItems": [] },
      "expectedTestAppValue": "Error: Error: cartItems must be a non-empty array"
    },
    {
      "title": "UpdateCartStatus API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_updateCartStatus",
      "inputValue": { "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729", "cartStatus": "Processed" },
      "expectedTestAppValue": "{\"id\":\"90dccefe-d23a-497d-9cb7-881bb5aaf729\",\"version\":{\"majorVersion\":1,\"minorVersion\":0},\"cartInfo\":{\"status\":\"Processed\",\"market\":\"US\",\"currency\":\"USD\",\"intent\":\"TeamsAdminUser\",\"locale\":\"en-US\",\"createdAt\":\"2021-09-30T15:00:00.000Z\",\"updatedAt\":\" 2021-09-30T15:00:00.000Z\"},\"cartItems\":[{\"id\":\"1\",\"name\":\"Item 1\",\"price\":10,\"quantity\":1,\"accessories\":[{\"id\":\"11\",\"name\":\"Item 11\",\"price\":5,\"quantity\":1,\"imageURL\":\"https://via.placeholder.com/150\"}]}]}"
    },
    {
      "title": "UpdateCartStatus API Call - Invalid Status",
      "type": "callResponse",
      "boxSelector": "#box_updateCartStatus",
      "inputValue": { "cartId": "90dccefe-d23a-497d-9cb7-881bb5aaf729", "cartStatus": "InvalidStatus" },
      "expectedTestAppValue": "Error: Error: cartStatus InvalidStatus is not valid"
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/mail.handoff.json
{
  "name": "Handoff ComposeMail",
  "version": ">2.0.0-beta.0",
  "platforms": "*",
  "featureTests": [
    {
      "feature": {
        "id": "mail.handoff",
        "version": 1
      },
      "testCases": [
        {
          "title": "checkMailWithHandoffCapability API Call - Success",
          "type": "callResponse",
          "boxSelector": "#box_checkMailWithHandoffCapability",
          "expectedTestAppValue": "MailWithHandoff module is supported"
        },
        {
          "title": "mail.handoff.composeMail Feature Test - Version 1",
          "type": "callResponse",
          "version": ">2.0.0-beta.0 && <=2.17.0",
          "boxSelector": "#box_composeMailWithHandoff",
          "inputValue": {
            "composeMailParams": {
              "type": "new",
              "subject": "Test Mail",
              "toRecipients": ["sam@example.com", "sam1@example.com"],
              "ccRecipients": ["sam2@example.com"],
              "bccRecipients": ["sam3@example.com"],
              "message": "This mail has been sent from the Teams Test App"
            },
            "handoffId": "abc123"
          },
          "expectedAlertValue": "composeMailParamsWithHandoff called with {\"type\":\"new\",\"subject\":\"Test Mail\",\"toRecipients\":[\"sam@example.com\",\"sam1@example.com\"],\"ccRecipients\":[\"sam2@example.com\"],\"bccRecipients\":[\"sam3@example.com\"],\"message\":\"This mail has been sent from the Teams Test App\"} and handoffId: abc123",
          "expectedTestAppValue": "Completed"
        },
        {
          "title": "mail.handoff.composeMail Feature Test with invalid handoffId- Failure",
          "type": "callResponse",
          "version": ">2.0.0-beta.0 && <=2.17.0",
          "boxSelector": "#box_composeMailWithHandoff",
          "inputValue": {
            "composeMailParams": {
              "type": "new",
              "subject": "Test Mail",
              "toRecipients": ["sam@example.com", "sam1@example.com"],
              "ccRecipients": ["sam2@example.com"],
              "bccRecipients": ["sam3@example.com"],
              "message": "This mail has been sent from the Teams Test App"
            },
            "handoffId": ""
          },
          "expectedTestAppValue": "Error: Error: handoffId should not be null or empty string."
        },
        {
          "title": "mail.handoff.composeMail Feature Test with invalid email - Failure",
          "type": "callResponse",
          "version": ">2.0.0-beta.0 && <=2.17.0",
          "boxSelector": "#box_composeMailWithHandoff",
          "inputValue": {
            "composeMailParams": {
              "type": "new",
              "subject": "Test Mail",
              "toRecipients": ["mockEmail", "sam1@example.com"],
              "ccRecipients": ["sam2@example.com"],
              "bccRecipients": ["sam3@example.com"],
              "message": "This mail has been sent from the Teams Test App"
            },
            "handoffId": "mockId"
          },
          "expectedTestAppValue": "Error: Error: Input email address does not have the correct format."
        }
      ]
    }
  ]
}

=== OfficeDev/microsoft-teams-library-js/apps/teams-test-app/e2e-test-data/secondaryBrowser.json
{
  "name": "SecondaryBrowser",
  "version": ">=2.12.0",
  "platforms": "iOS",
  "checkIsSupported": {},
  "testCases": [
    {
      "title": "openUrl API Call - Success",
      "type": "callResponse",
      "boxSelector": "#box_secondaryBrowser_open",
      "inputValue": "https://www.bing.com",
      "expectedSecondViewTarget": "SFSafariViewController"
    }
  ]
}
